USE RetailDW;

GO

-- creation of the DimProuct table
CREATE TABLE DimProduct(
	ProductKey INT IDENTITY(1,1) PRIMARY KEY,
	ProductID VARCHAR(50) NOT NULL UNIQUE,
	ProductName VARCHAR(100) NOT NULL, 
	Category VARCHAR(100) NULL, 
	Price DECIMAL(18,2) NOT NULL, 
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME2 NOT NULL DEFAULT GETDATE()
);
