USE RetailDW;

GO

CREATE TABLE DimStore(
	StoreKey INT IDENTITY(1,1) PRIMARY KEY, 
	StoreID  INT NOT NULL UNIQUE, 
	StoreName VARCHAR(100) NOT NULL, 
	City VARCHAR(100) NULL, 
	State VARCHAR(100) NULL
);
	