USE RetailDW;

GO 

CREATE TABLE FileImports (
	FileImportID INT IDENTITY(1,1) PRIMARY KEY, 
	FileName VARCHAR(255) NOT NULL, 
	ArchivePath VARCHAR(500) NULL, 
	FileImportStatus VARCHAR(50) NOT NULL, 
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(), 
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
);
